Update patch set 1
Patch Set 1: Fails

This is an automated message from the Deckard Autoverifier:

This patchset fails to build in the public AOSP source tree.  The following snippet of output from `make` may point you in the right direction:

build/tools/aprof/Aprof.cpp:21:22: error: libaprof.h: No such file or directory
build/tools/aprof/Aprof.cpp: In member function ‘bool Aprof::readHeader(FILE*)’:
build/tools/aprof/Aprof.cpp:108: error: ‘APROF_TAG’ was not declared in this scope
build/tools/aprof/Aprof.cpp:109: error: ‘APROF_TAG_LENGTH’ was not declared in this scope
build/tools/aprof/Aprof.cpp:114: error: ‘tag’ was not declared in this scope
build/tools/aprof/Aprof.cpp: In member function ‘bool Aprof::readProfileFile()’:
build/tools/aprof/Aprof.cpp:146: error: ‘APROF_EXECUTABLE_HISTOGRAM_HEADER’ was not declared in this scope
build/tools/aprof/Aprof.cpp:150: error: ‘APROF_HISTOGRAM_HEADER’ was not declared in this scope
build/tools/aprof/Aprof.cpp:154: error: ‘APROF_CALL_GRAPH_HEADER’ was not declared in this scope
make: *** [out/host/linux-x86/obj/EXECUTABLES/aprof_intermediates/Aprof.o] Error 1

If your patchset has a dependency in a separate project and you believe that this is the cause of the breakage, a reviewer can verify +1 and Deckard will remove the verify -1 shortly thereafter.

Otherwise, if you wish to pursue this change, please fix the error and upload a new patchset.

Thanks!

Patch-set: 1
Label: Code-Review=0