Update patch set 8
Patch Set 8: Presubmit-Ready+1

> Patch Set 8: Code-Review+1

Got an error in taimen-userdebug. I'm guessing this isn't realted to this CL and since I'm new I'm not sure who to talk to.

Error while processing /mnt/disks/build-disk/src/googleplex-android/master/hardware/qcom/camera/msm8998/QCamera2/HAL3/QCamera3HWI.cpp.
/mnt/disks/build-disk/src/googleplex-android/master/hardware/qcom/camera/msm8998/QCamera2/HAL3/QCamera3HWI.cpp:11764:65: error: missing field 'stream_configuration_counter' initializer [clang-diagnostic-missing-field-initializers]

Patch-set: 8
Reviewer: Gerrit User 1426851 <1426851@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=+1