Find the jar libraries in APEX from the correct path
JAR libraries in the ART and conscrypt APEXes are no longer built for
the platform. Therefore, the path out/target/common/<name>_intermediates
does not exist. Instead use the path
out/target/common/<libname>.<apexname>_intermediates paths for those
APEX-only jars.

Bug: 128708192
Bug: 133140750
Test: m
Test: m libnativeloader doesn't install anything. (because it doesn't
have "//apex_available:platform".
Test: Add "libnativeloader" to shared_libs of "libvndksupport" which is
installed to /system/lib. Then the build fails with following error.

error: system/core/libvndksupport/Android.bp:3:1: module "libvndksupport" variant "android_arm_armv8-a_core_shared": depends on //art/libnativeloader:libnativeloader which is not visible to this module

Change-Id: I5fb725403ac22198e5ce6d77ca97c5f3392fabfd