core: Makefile: Depend on INTERNAL_OTATOOLS_FILES
Signapk should be a dependency of the otapackage target, but
signapk (as part of INTERNAL_OTATOOLS_FILES) has only been
required so far for otatools, otardppackage and partialotapackage

Without this change, running `m otapackage` fails with this
error if `m signapk` was not previously run manually:

```
2021-02-06 01:00:21 - common.py - INFO    :   Running: "java -Xmx2048m -Djava.library.path=out/host/linux-x86/lib64 -jar out/host/linux-x86/framework/signapk.jar -w build/make/target/product/security/testkey.x509.pem build/make/target/product/security/testkey.pk8 /home/builder/workdir/out/soong/.temp/tmpTssuv1.zip /home/builder/workdir/out/soong/.temp/tmp6cAr4d.zip"
2021-02-06 01:00:21 - ota_from_target_files.py - ERROR   :
   ERROR:
Traceback (most recent call last):
  File "/home/builder/workdir/out/host/linux-x86/bin/ota_from_target_files/ota_from_target_files.py", line 2258, in <module>
  File "/home/builder/workdir/out/host/linux-x86/bin/ota_from_target_files/ota_from_target_files.py", line 2231, in main
  File "/home/builder/workdir/out/host/linux-x86/bin/ota_from_target_files/ota_from_target_files.py", line 1932, in GenerateAbOtaPackage
  File "/home/builder/workdir/out/host/linux-x86/bin/ota_from_target_files/ota_from_target_files.py", line 1328, in FinalizeMetadata
  File "/home/builder/workdir/out/host/linux-x86/bin/ota_from_target_files/ota_from_target_files.py", line 1314, in ComputeAllPropertyFiles
  File "/home/builder/workdir/out/host/linux-x86/bin/ota_from_target_files/ota_from_target_files.py", line 492, in SignOutput
  File "/home/builder/workdir/out/host/linux-x86/bin/ota_from_target_files/common.py", line 1847, in SignFile
    proc.returncode, stdoutdata))
ExternalError: Failed to run signapk.jar: return code 1:
Error: Unable to access jarfile out/host/linux-x86/framework/signapk.jar
```

Change-Id: I04f333671c37095766e3ac9a62325092dcc31c8a

Signed-off-by: Felix Elsner <google@ix5.org>
Change-Id: Ieb6c0041713f5c5943b39e98d81f13940bbf69a3