fsconfig: fix error message for duplicate AID
Fixes:
    raise ValueError('Duplicate aid value "%u" for %s' % value,
TypeError: %u format: a number is required, not str

and

    raise ValueError('Duplicate aid value "%s" for %s' % value,
TypeError: not enough arguments for format string

Test: See unit test on: Change-Id: I3b2285f15d6d8d6c8053fd2460202cbc033e6ca4

Change-Id: I10376df84288d63713c08258e3fd34024561e483
Signed-off-by: William Roberts <william.c.roberts@intel.com>