Fixing compilation issue beacause of python version
TypeError: a bytes-like object is required, not 'NoneType'

Change-Id: I0d7fa4fd392ee2c53254890f0a60a473d96d8e20