Update patch set 1
Patch Set 1:

Ying, could you help me to look at this. Its broadly working but if you follow the instructions you'll see failed imports. e.g.
packages/apps/Exchange/src/com/android/exchange/Exchange.java:21: error: cannot find symbol
import com.android.emailcommon.provider.EmailContent;
This is either a missing jar files, missing dependencies or a jar file was created containing no class files. If I do a "mm" build in the project they work, which makes me think this is a dependency issue.
Thanks!

Patch-set: 1
Label: Verified=0