Add bionic include paths are added as system headers
Include path for libc headers (bionic/libc/include) has been added
twice. Once via -I and once via -isystem. Since -I <a_path> is ignored
when -isystem <a_path> exists, bionic/libc/include has always been
recognized as a system include path (= has lower priority than other -I
paths).

However, when LOCAL_USE_VNDK is set for a module, -isystem
bionic/libc/include is not added. As a result, -I bionic/libc/include is
respected and this causes #include <stdlib.h> in a C++ header to load
bionic/libc/include/stdlib.h instead of the intended
external/libcxx/include/stdlib.h (, which internally includes the bionic
stdlib.h).

Not including external/libcxx/include/stdlib.h causes several warnings
and errors when using C++ headers. For example, #include <memory> gives
following error:

bionic/libc/include/wchar.h:133:40: error: pointer is missing a
nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)
[-Werror,-Wnullability-completeness]
FILE* open_wmemstream(wchar_t**, size_t*) __INTRODUCED_IN(23);

In order to solve the problem, TARGET_C_SYSTEM_INCLUDES (which has the
bionic header paths) is added even when LOCAL_USE_VNDK is true.

Bug: 63313808
Test: build with BOARD_VNDK_VERSION=current does not cause errors on C++
headers.

Change-Id: If555e237fa29bbf01211338ebddf1e6648c83d58