Update patch set 1
Patch Set 1: Verified+1 Autosubmit+1 Presubmit-Ready+1

(1 comment)

With https://android-review.googlesource.com/c/platform/build/+/1157701/, dynamic_partitions_info.txt is now generated using core/Makefile:dump-dynamic-partitions-info. This has changed the contents of the file, and the merge_target_files.py script also needs an update.

This fixes an error which manifests as:

Traceback (most recent call last):
  File "/tmp/merge_rJIYZw/otatools/releasetools/merge_target_files.py", line 1077, in <module>
    main()
  File "/tmp/merge_rJIYZw/otatools/releasetools/merge_target_files.py", line 1073, in main
    rebuild_recovery=OPTIONS.rebuild_recovery), OPTIONS.keep_tmp)
  File "/tmp/merge_rJIYZw/otatools/releasetools/merge_target_files.py", line 929, in call_func_with_temp_dir
    func(temp_dir)
  File "/tmp/merge_rJIYZw/otatools/releasetools/merge_target_files.py", line 1073, in <lambda>
    rebuild_recovery=OPTIONS.rebuild_recovery), OPTIONS.keep_tmp)
  File "/tmp/merge_rJIYZw/otatools/releasetools/merge_target_files.py", line 877, in merge_target_files
    rebuild_recovery)
  File "/tmp/merge_rJIYZw/otatools/releasetools/merge_target_files.py", line 729, in create_merged_package
    framework_misc_info_keys=framework_misc_info_keys)
  File "/tmp/merge_rJIYZw/otatools/releasetools/merge_target_files.py", line 611, in process_special_cases
    output_target_files_dir=output_target_files_temp_dir)
  File "/tmp/merge_rJIYZw/otatools/releasetools/merge_target_files.py", line 488, in process_dynamic_partitions_info_txt
    list_suffix='_partition_list')
  File "/tmp/merge_rJIYZw/otatools/releasetools/common.py", line 832, in MergeDynamicPartitionInfoDicts
    raise ValueError("Vendor dict does not contain required key %s." % key)
ValueError: Vendor dict does not contain required key foo_dynamic_partitions_size.

The new name for the key is "super_foo_dynamic_partitions_group_size".

Patch-set: 1
Reviewer: Gerrit User 1455782 <1455782@85c56323-6fa9-3386-8a01-6480fb634889>
Reviewer: Gerrit User 1278180 <1278180@85c56323-6fa9-3386-8a01-6480fb634889>
Reviewer: Gerrit User 1088085 <1088085@85c56323-6fa9-3386-8a01-6480fb634889>
Reviewer: Gerrit User 1286860 <1286860@85c56323-6fa9-3386-8a01-6480fb634889>
CC: Gerrit User 1121838 <1121838@85c56323-6fa9-3386-8a01-6480fb634889>
Reviewer: Gerrit User 1340374 <1340374@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Verified=+1
Label: Autosubmit=+1
Label: Presubmit-Ready=+1