Update patch set 1
Patch Set 1: Verified; Looks good to me, approved

[admin override - clean revert to fix build]

Kan-Ru, unfortunately your earlier change broke the Windows SDK build. We'll gladly accept a revised change that takes that configuration into account. Sorry for the annoyance.

$ make PRODUCT-sdk-win_sdk
[...]
host C: libhost <= build/libs/host/CopyFile.c
build/libs/host/CopyFile.c: In function ‘setPermissions’:
build/libs/host/CopyFile.c:157: error: ‘const struct stat’ has no member named ‘st_mtim’
make[1]: *** [out/host/windows-x86/obj/STATIC_LIBRARIES/libhost_intermediates/CopyFile.o] Error 1

Patch-set: 1
Reviewer: Gerrit User 1000660 <1000660@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Code-Review=+2
Label: SUBM=+1
Label: Verified=+1