Update patch set 2
Patch Set 2: Verified-1

this breaks the x86 build in at least two places:

external/clang/lib/include/emmintrin.h:28:2: error: "SSE2 instruction set not enabled"
#error "SSE2 instruction set not enabled"
 ^

and

external/scrypt/lib/crypto/crypto_scrypt-sse.c:51:23: error: unknown type name '__m128i'
static void salsa20_8(__m128i *);
                      ^

Patch-set: 2
Label: Verified=-1