Update patch set 1
Patch Set 1:

Two projects fail with this patches:

1. libjni_jpegutil in packages/apps/Camera2/jni/Android.mk needs libjpeg.so not available in NDK.  May fail to load on device w/o libjpeg.so, or not all the functions libjni_jpeguti needs exist.

packages/apps/Camera2/jni/jpegutil.cpp:168: error: undefined reference to 'jpeg_std_error'
packages/apps/Camera2/jni/jpegutil.cpp:187: error: undefined reference to 'jpeg_destroy_compress'
packages/apps/Camera2/jni/jpegutil.cpp:197: error: undefined reference to 'jpeg_CreateCompress'
packages/apps/Camera2/jni/jpegutil.cpp:245: error: undefined reference to 'jpeg_set_defaults'
packages/apps/Camera2/jni/jpegutil.cpp:247: error: undefined reference to 'jpeg_set_quality'
packages/apps/Camera2/jni/jpegutil.cpp:253: error: undefined reference to 'jpeg_set_colorspace'
packages/apps/Camera2/jni/jpegutil.cpp:262: error: undefined reference to 'jpeg_start_compress'
packages/apps/Camera2/jni/jpegutil.cpp:285: error: undefined reference to 'jpeg_write_raw_data'
packages/apps/Camera2/jni/jpegutil.cpp:288: error: undefined reference to 'jpeg_finish_compress'
packages/apps/Camera2/jni/jpegutil.cpp:300: error: undefined reference to 'jpeg_destroy_compress'


2. libssl in external/boringssl/Android.mk needs libcrypto.so not available in NDK

libssl is okay for now because libcrypto.so is built in the same Android.mk.  But we needs better way to ensure that systematically.

Patch-set: 1