fs_config: correctly handle integer values when 0
Fixes compile error:
error: use of undeclared identifier 'CAP_0'
   { 0777    ,AID_XXX    ,AID_XXX    ,(1ULL << CAP_0)    ,"/system/bin/xxx" },

convert_int(num) was failing when num was 0. Since 0 is
false in Python. Rather than going through the convert_int()
maze, just use int() with a base of 0. When the base is set
to 0, int() correctly converts base.

test: Verify that 0's get converted correctly.
      Verify that existing config.fs files have the same hash.

Change-Id: I65ecfcca83b4274017f70692277594f6f9edf867
Signed-off-by: William Roberts <william.c.roberts@intel.com>