releasetools: support prebuilt vendor.img
Following https://source.android.com/devices/tech/ota/sign_builds#release-keys
and https://source.android.com/devices/tech/ota/sign_builds#creating-image-files
causes the following error for devices with prebuilt vendor.img:

Traceback (most recent call last):
  File "./build/make/tools/releasetools/sign_target_files_apks", line 1230, in <module>
    main(sys.argv[1:])
  File "./build/make/tools/releasetools/sign_target_files_apks", line 1223, in main
    add_img_to_target_files.main(new_args)
  File ".../build/make/tools/releasetools/add_img_to_target_files.py", line 942, in main
    AddImagesToTargetFiles(args[0])
  File ".../build/make/tools/releasetools/add_img_to_target_files.py", line 892, in AddImagesToTargetFiles
    CheckAbOtaImages(output_zip, ab_partitions)
  File ".../build/make/tools/releasetools/add_img_to_target_files.py", line 562, in CheckAbOtaImages
    assert available, "Failed to find " + img_name
AssertionError: Failed to find vendor.img

This patch addresses this error by copying IMAGES/vendor.img if it exists in the
input zip

Change-Id: I903ff20d79bcf7621ebf29f0b8dfe85ebc3fb1ff