Use apex_available property
Use apex_available property to prevent modules that are only for the ART
apex from being used outside of the APEX.

Bug: 128708192
Bug: 133140750
Bug: 129006418
Test: m
Test: m libnativeloader doesn't install anything. (because it doesn't
have "//apex_available:platform".
Test: Add "libnativeloader" to shared_libs of "libvndksupport" which is
installed to /system/lib. Then the build fails with following error.

error: system/core/libvndksupport/Android.bp:3:1: module
"libvndksupport" variant "android_arm_armv8-a_core_shared": depends on
//art/libnativeloader:libnativeloader which is not visible to this
module

Change-Id: I964d0125cfedb454a60c098bf1a1797201d5dd40