Update patch set 2
Patch Set 2: Verified-1

Causes:
ERROR: resource directory 'out/target/common/obj/APPS/RsHelloCompute_intermediates/renderscript/res' does not exist
when running aapt package.

Patch-set: 2
Reviewer: Gerrit User 1002751 <1002751@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Verified=-1