Update patch set 1
Patch Set 1:

Chih-Wei,

Have you verified this fix with setting the TARGET_ARCH_VARIANT? Dalvik didn't build for me when I merged this into my private tree. I doubt that my private changes caused this.

dalvik/vm/mterp/out/InterpAsm-x86-atom.S:18086: undefined reference to `.L_OP_UNUSED_EC'
dalvik/vm/mterp/out/InterpAsm-x86-atom.S:18086: undefined reference to `.L_OP_UNUSED_EF'

Patch-set: 1