Update patch set 1
Patch Set 1:

We may need to fix our headers before submitting this change.

In file included from prebuilts/ndk/current/sources/cxx-stl/stlport/stlport/math.h:32:
prebuilts/ndk/current/platforms/android-8/arch-arm/usr/include/../include/math.h:527:5: error: conflicting types for '__builtin_isnan'
int     __builtin_isnan(double) __NDK_FPABI_MATH__ __pure2;
        ^
prebuilts/ndk/current/platforms/android-8/arch-arm/usr/include/../include/math.h:527:5: note: '__builtin_isnan' is a builtin with type 'int ()'

Patch-set: 1