Update patch set 2
Patch Set 2:

The treehugger failure is related, but I'm not sure what's happening:
FAILED: out/target/product/generic_x86_64/obj/APPS/DtsSampleAndroidActivityLifecycleApplication_intermediates/DtsSampleAndroidActivityLifecycleApplication.config 
/bin/bash -c "(rm -f out/target/product/generic_x86_64/obj/APPS/DtsSampleAndroidActivityLifecycleApplication_intermediates/DtsSampleAndroidActivityLifecycleApplication.config ) && (build/make/tools/auto_gen_test_config.py out/target/product/generic_x86_64/obj/APPS/DtsSampleAndroidActivityLifecycleApplication_intermediates/DtsSampleAndroidActivityLifecycleApplication.config out/target/common/obj/APPS/DtsSampleAndroidActivityLifecycleApplication_intermediates/AndroidManifest.xml build/make/core/empty_test_config.xml build/make/core/instrumentation_test_config_template.xml )"
...
IOError: [Errno 2] No such file or directory: 'out/target/common/obj/APPS/DtsSampleAndroidActivityLifecycleApplication_intermediates/AndroidManifest.xml'

It looks like there is a dependency on the missing file, so it should be present when the rule runs.  Maybe the rule that is supposed to output the missing isn't actually writing it, or something else is deleting it?

Patch-set: 2
Reviewer: Gerrit User 1002751 <1002751@85c56323-6fa9-3386-8a01-6480fb634889>