Update patch set 1
Patch Set 1: Code-Review+1 Verified+1

This fixes otapackage on master

I still see an error but it doesn't seem fatal
[0327/135917.451704:INFO:delta_diff_generator.cc(127)] All done. Successfully created delta file with metadata size = 33475
Done generating full update.
2020-03-27 13:59:17 - common.py - INFO    : 
2020-03-27 13:59:17 - common.py - INFO    :   Running: "delta_generator --out_maximum_signature_size_file=/home/luca/android/aosp/out/soong/.temp/signature_size8eS19b --private_key=/home/luca/android/aosp/out/soong/.temp/key-8gP4nQ.key"
2020-03-27 13:59:17 - common.py - INFO    : 
Traceback (most recent call last):
  File "/home/luca/android/aosp/out/host/linux-x86/bin/ota_from_target_files/internal/stdlib/logging/__init__.py", line 868, in emit
    msg = self.format(record)
  File "/home/luca/android/aosp/out/host/linux-x86/bin/ota_from_target_files/internal/stdlib/logging/__init__.py", line 741, in format
    return fmt.format(record)
  File "/home/luca/android/aosp/out/host/linux-x86/bin/ota_from_target_files/internal/stdlib/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/home/luca/android/aosp/out/host/linux-x86/bin/ota_from_target_files/internal/stdlib/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: %o format: a number is required, not str

Patch-set: 1
Reviewer: Gerrit User 1081223 <1081223@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Verified=+1
Label: Code-Review=+1