fixup! Support generating partial OTAs from extracted target_files
Commit 6b10e15acc35f7ff48a0e17e5dadbf9e814f7686 introduced a typo, where paht was used instead of path.

This leads to the following compilation error:

GetTargetFilesZipForRetrofitDynamicPartitions
AttributeError: module 'os' has no attribute 'paht'

Change-Id: I7f67361a69a5b528d2f897bc5684d89944b9382a
Signed-off-by: rk134 <rahul@aospa.co>