Update patch set 2
Patch Set 2: Verified-1

Failed to 'make dist' for cf_x86_phone-userdebug.

  Running: "openssl pkcs8 -in build/target/product/security/testkey.pk8 -inform DER -nocrypt"
unable to load device-specific module; assuming none
building image from target_files RECOVERY...
Traceback (most recent call last):
  File "build/make/tools/releasetools/ota_from_target_files", line 2047, in <module>
    main(sys.argv[1:])
  File "build/make/tools/releasetools/ota_from_target_files", line 2021, in main
    output_file=args[1])
  File "build/make/tools/releasetools/ota_from_target_files", line 841, in WriteFullOTAPackage
    allow_shared_blocks)
  File "/usr/local/google/home/bowgotsai/codebase/disk2/0629_aosp/build/make/tools/releasetools/common.py", line 753, in GetSparseImage
    hashtree_info_generator=hashtree_info_generator)
  File "/usr/local/google/home/bowgotsai/codebase/disk2/0629_aosp/build/make/tools/releasetools/sparse_img.py", line 53, in __init__
    raise ValueError("Magic should be 0xED26FF3A but is 0x%08X" % (magic,))
ValueError: Magic should be 0xED26FF3A but is 0x00000000
17:51:38 ninja failed with: exit status 1

Patch-set: 2
Reviewer: Gerrit User 1080813 <1080813@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Verified=-1